name: amo_gym_rayan
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - matplotlib
  # Core scientific python
  - numpy
  - pandas
  # Reiforcement Learning algorithms
  - gym 
  - stable_baselines3
  - tensorflow
  # Technical analysis for features
  - ta
  # MetaTrader5 and timezone helper
  - MetaTrader5
